### ISSUE TITLE
Level up error!!! 

### ISSUE THREAD

**Issue by Pawansingh333** [SkalaFrost/TabiZooBot#1]
Level up error!!! - Cannot connect to host api.tabibot.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by SkalaFrost** [comment]
Please report any errors on the TG channel. Thank you for your understanding.
