### ISSUE TITLE
Unknown error during Authorization: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by dsmddsmd** [SkalaFrost/TabiZooBot#4]
![messageImage_1726994216855](https://github.com/user-attachments/assets/72d0e402-b026-4068-82af-1d9a1c77691f)
Unknown error during Authorization: 'int' object has no attribute 'encode'

**Comment by SkalaFrost** [comment]
update to the latest version and contact me if u have any issues.

**Comment by dsmddsmd** [comment]
> update to the latest version and contact me if u have any issues.

![Screenshot_563](https://github.com/user-attachments/assets/0fb256ec-a429-40da-8953-3d059a6e7b3c)
