### ISSUE TITLE
 peer_type = utils.get_peer_type(peer_id)   File "C:\Users\5600x\TabiZooBot\venv\lib\site-packages\pyrogram\utils.py", line 246, in get_peer_type     raise ValueError(f"Peer id invalid: {peer_id}")

### ISSUE THREAD

**Issue by dsmddsmd** [SkalaFrost/TabiZooBot#5]
![369678041-0fb256ec-a429-40da-8953-3d059a6e7b3c](https://github.com/user-attachments/assets/0328b21d-59b0-483d-b384-ba976d79677d)

**Comment by hardwin1014** [comment]
The id of the group channel is incorrect

**Comment by SkalaFrost** [comment]
im trying to find out the root cause, please stay tuned.
